### ISSUE TITLE
split vertically in portrait mode?

### ISSUE THREAD

**Issue by yeahman45** [tberghuis/watch-and-read-comments-for-youtube#31]
I am using this extension on my chromebook/tablet on chrome. It is super useful for landscape mode reading the comments while watching the video like on the android app but it is not great when in portrait mode.
Is it possible to add a feature to split it vertically when in portrait mode?

**Comment by tberghuis** [comment]
You should use the mobile version of youtube, place m. at start of URL like https://m.youtube.com/ 
if that doesn't work try https://m.youtube.com/?persist_app=1&app=m

**Comment by yeahman45** [comment]
there's no "pip" mini player and gesture support on the mobile version of youtube unfortunately.

**Comment by yeahman45** [comment]
I will just develop something. thx for your code inspiring me :)
