### ISSUE TITLE
Empty comments & related tabs

### ISSUE THREAD

**Issue by ChromiaCat** [tberghuis/watch-and-read-comments-for-youtube#35]
As the title says, a few days ago the comments & related tabs are empty, only the description tab has content. I'm suspect of a YT layout but I'm not familiar with making extensions to figure that out.

**Comment by tberghuis** [comment]
Yes fixes has been made in branch dev-july-2022. 
Submitted to google waiting for approval, the initial fix had bugs so once that is approved, will submit latest fix which will then have to wait for approval.
