### ISSUE TITLE
Playlists don't show up & extension buttons don't have borders

### ISSUE THREAD

**Issue by ChromiaCat** [tberghuis/watch-and-read-comments-for-youtube#36]
I guess it's another YT layout change but whatever it is, here's a snip for your reference
![image](https://user-images.githubusercontent.com/43613021/183266669-00ddcd57-ab97-4af2-b765-c24d426b13a6.png)

**Comment by tberghuis** [comment]
Yes fix has been made and submitted to google, waiting for approval, usually takes a few days.

**Comment by ChromiaCat** [comment]
Since it's been fixed and waiting for approval I'll close this issue.
