### ISSUE TITLE
Related videos list needs a refresh to disappear.

### ISSUE THREAD

**Issue by ChromiaCat** [tberghuis/watch-and-read-comments-for-youtube#45]
Extension fails to hide the related videos list and needs a tab refresh to work properly.

**Comment by ChromiaCat** [comment]
Update: Seems an extension is causing the issue, will try to isolate.

**Comment by ChromiaCat** [comment]
I had posted an update that some extension was causing this one to break and need a refresh to work, after disabling all others and leaving only WARC it still fails to hide related videos, so it's WARC that has a bug.

If it helps I dived into the element the extension's supposed to add the CSS code that hides it and it seems to somehow fail in adding that CSS code to the appropriate DIV element for related videos, but succeeds in doing it to the other stuff it's supposed to. And somehow a refresh fixes it.

Edit: It seems that in addition to not hiding related videos it also doesn't properly resize the video playing until a refresh.
![image](https://github.com/tberghuis/watch-and-read-comments-for-youtube/assets/43613021/6dff1dd4-8a4f-453a-b78b-90388586ce45)
This is a snippet of a freshly opened incognito window, it also happens on regular tabs. Don't mind the different color around the page, I'm using Stylus to change the color of stuff in YouTube. And no, Stylus doesn't cause this, read the top first sentence I wrote.

**Comment by tberghuis** [comment]
I can't reproduce. 
What version of the extension are you running?

**Comment by ChromiaCat** [comment]
0.5.1 on Chrome 115.0.5790.99

**Comment by ChromiaCat** [comment]
Hello, discard this issue as it seems to have been an issue with my browser.
Thanks for your time anyways.

**Comment by ChromiaCat** [comment]
Nevermind, the issue is back, this time I bothered to check the console and look what it printed:
![image](https://github.com/tberghuis/watch-and-read-comments-for-youtube/assets/43613021/c1cbd68f-8b23-46d0-bc3c-8dbf50dee7fd)
This error pops up whenever it fails to hide the videos list, but doesn't when I refresh.
If you need me to provide additional info let me know.

**Comment by tberghuis** [comment]
Thanks for reporting. Will fix tomorrow, then google normally takes a day to approve new version.

**Comment by ChromiaCat** [comment]
> Thanks for reporting. Will fix tomorrow, then google normally takes a day to approve new version.

Nice, you fixed it. Do you mind if I make a PR to stop the description from auto-expanding?

**Comment by tberghuis** [comment]
If you make it a checkbox option in popup (autoexpand = true by default) I will accept because I purposely made it do that.

**Comment by ChromiaCat** [comment]
> If you make it a checkbox option in popup (autoexpand = true by default) I will accept because I purposely made it do that.

Oh, I don't have that kinda skill in JS to do that 😅
I have edited out the part that expands it locally, other than that props for fixing the video list issue.
